### ISSUE TITLE
Create Docker Compose Resources for Running OBAM with OBKM on MySQL Database for Berlin Spec

### ISSUE THREAD

**Issue by kdanW** [wso2/docker-open-banking#25]
**Description:**
Currently the Docker-Compose resources are available only for UK specification.  Docker-Compose resources should be created for the Berlin specification.

**Affected Product Version:**
v1.4.0

**OS, DB, other environment details and versions:**    
MySQL

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/docker-open-banking/pull/29.
