### ISSUE TITLE
MySQL container resets max_connections during runtime.

### ISSUE THREAD

**Issue by kaumini** [wso2/docker-open-banking#30]
**Description:**
The MySQL 5.7 container restarts after executing the script, which resets the max_connections to 151(Default value). The setting of max_connections at the beginning is not permanent.

**Comment by chirangaalwis** [comment]
@kaumini shall we raise a question at the Official MySQL Docker image source repository [1], referring this issue?

[1]: [Official MySQL Docker image source repository](https://github.com/docker-library/mysql/issues)

**Comment by kaumini** [comment]
Added an issue https://github.com/docker-library/mysql/issues/598

**Comment by kaumini** [comment]
The max_connections of the MySQL container should be set by updating the my.cnf file at /etc/mysql/ of MySQL container. Add the following to the my.cnf

> [mysqld]
> max_connections = 1000

To increase the max_connections, then the ulimit in the container should be large enough. (docker run and compose file). ulimits can be set as below

> ulimits:
>>     nofile:
>>     soft: 20000
>>     hard: 40000

**Comment by kaumini** [comment]
Fixed with #31
