### ISSUE TITLE
Local Entries folder not created in OBAM-OBKM-with-OBBI profile

### ISSUE THREAD

**Issue by kdanW** [wso2/docker-open-banking#34]
**Description:**
In the above profile local-entries folder is not created in /repository/deployment/server/synapse-configs/default path. Due to this API calls cannot be executed.

**Comment by kdanW** [comment]
This error is due to incorrect mount path in registry.xml for the registry DB. This can be resolved by correcting it.

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/docker-open-banking/pull/35.
