### ISSUE TITLE
Failure to accept product startup options

### ISSUE THREAD

**Issue by kdanW** [wso2/docker-open-banking#43]
**Description:**
Currently the Docker entrypoint scripts in WSO2 Open Banking use shell scripts. Need to convert them to bash script.
Will have to install bash in alpine for this as well.
This is needed as the current script doesn't allow passing startup options

**Comment by chirangaalwis** [comment]
@kdanW the original issue is the inability to pass product startup options to WSO2 OB API Manager Docker deployments. Hence, changing the title accordingly.

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/docker-open-banking/pull/44.
