### ISSUE TITLE
Preserve the default H2 database data required for Solr indexing process

### ISSUE THREAD

**Issue by kaumini** [wso2/docker-open-banking#46]
**Description:**
It is required to mount to the <OBAM_HOME>/repository/database directory for persistence 

**Affected Product Version:**
Docker resources for WSO2 Open Banking API Manager v1.4.x

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/docker-open-banking/pull/44/files#diff-1b6e37e4e08cff2e9a4a02e2f5ed0bf9.
