### ISSUE TITLE
Create Docker resources for WSO2 Open Banking version 1.5.0

### ISSUE THREAD

**Issue by thiloshon** [wso2/docker-open-banking#57]
**Description:**
Dockerfile for Open Banking API Manager(OBAM) should be created to build the OBAM based on adoptopenjdk:11.0.6_10-jdk-hotspot-bionic image and run the server

**Affected Product Version:**
OB 1.5.0

**OS, DB, other environment details and versions:**    
ubuntu, alpine

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/docker-open-banking/pull/63.
