### ISSUE TITLE
Create Docker Compose Resources for Running OBAM and OBKM with OBBI on MySQL Database for version 1.5.0

### ISSUE THREAD

**Issue by thiloshon** [wso2/docker-open-banking#59]
**Description:**
Docker compose resources should be created to start Open Banking API Manager, Key Manager and Business Intelligence servers running on MySQL database.

**Affected Product Version:**
OB 1.5.0

**OS, DB, other environment details and versions:**    
mysql - 5.7.29

**Comment by chirangaalwis** [comment]
Fixed in referenced PR.
