### ISSUE TITLE
Create Docker resources for WSO2 Open Banking version 2.0.0

### ISSUE THREAD

**Issue by nalakagunathilaka** [wso2/docker-open-banking#90]
**Description:**
Create Dockerfiles for OBAM, OBKM and OBBI for Ubuntu based on adoptopenjdk:8u262-b10-jdk-hotspot-bionic image and for Alpine based on adoptopenjdk/openjdk8:jdk8u272-b10-alpine image. This effort is towards the OB 2.0 docker release.

**Affected Product Version:**
OB 2.0.0

**OS, DB, other environment details and versions:**
Ubuntu, Alpine

**Comment by chirangaalwis** [comment]
Fixed.
